import {
  Transaction,
  TransactionCategory,
  TransactionIconType,
  TransactionType,
} from '../interfaces/transaction.interface';

export const categoriesMock: TransactionCategory[] = [
  {
    id: '1',
    description: 'prestamos',
    name: 'prestamos',
    iconType: TransactionIconType.LEADING,
    color: '#ff7878',
  },
  {
    id: '2',
    description: 'salud',
    name: 'salud',
    iconType: TransactionIconType.HEALTH,
    color: '#74c8ff',
  },
  {
    id: '3',
    description: 'familia',
    name: 'familia',
    iconType: TransactionIconType.FAMILY,
    color: '#ff7878',
  },
  {
    id: '4',
    description: 'casa',
    name: 'casa',
    iconType: TransactionIconType.HOME,
    color: '#ff7878',
  },
  {
    id: '5',
    description: 'otros',
    name: 'otros',
    iconType: TransactionIconType.OTHERS,
    color: '#ff7878',
  },
  {
    id: '6',
    description: 'trabajo',
    name: 'trabajo',
    iconType: TransactionIconType.WORK,
    color: '#8181ff',
  },
  {
    id: '7',
    description: 'educación',
    name: 'educación',
    iconType: TransactionIconType.EDUCATION,
    color: '#d0ff78',
  },
  {
    id: '8',
    description: 'café',
    name: 'café',
    iconType: TransactionIconType.COFFEE,
    color: '#ffba78',
  },
  {
    id: '9',
    description: 'alimentación',
    name: 'alimentación',
    iconType: TransactionIconType.FOOD,
    color: '#78ff78',
  },
  {
    id: '10',
    description: 'regalo',
    name: 'regalo',
    iconType: TransactionIconType.GIFS,
    color: '#ff78c2',
  },
  {
    id: '11',
    description: 'rutina',
    name: 'rutina',
    iconType: TransactionIconType.ROUTINE,
    color: '#78ffac',
  },
  {
    id: '12',
    description: 'transporte',
    name: 'transporte',
    iconType: TransactionIconType.TRANSPORT,
    color: '#81ffff',
  },
];

export const transactionsMock: Transaction[] = [
  {
    id: '1',
    category: categoriesMock[0],
    date: new Date(2022, 4, 30, 15, 0, 0, 0),
    description: 'prestamo al vecino',
    mount: 5000,
    type: TransactionType.EXPENSIVE,
  },
  {
    id: '2',
    category: categoriesMock[1],
    date: new Date(2022, 6, 1, 14, 0, 0, 0),
    description: '5 acetaminofen',
    mount: 400,
    type: TransactionType.EXPENSIVE,
  },
  {
    id: '3',
    category: categoriesMock[2],
    date: new Date(2022, 6, 3, 11, 0, 0, 0),
    description: 'regalo del dia de las madres',
    mount: 2500,
    type: TransactionType.EXPENSIVE,
  },
  {
    id: '4',
    category: categoriesMock[3],
    date: new Date(2022, 6, 2, 18, 0, 0, 0),
    description: 'pago alquiler',
    mount: 15000,
    type: TransactionType.EXPENSIVE,
  },
  {
    id: '5',
    category: categoriesMock[4],
    date: new Date(2022, 3, 11, 16, 0, 0, 0),
    description: 'Bono del trabajo',
    mount: 5000,
    type: TransactionType.INCOMES,
  },
  {
    id: '6',
    category: categoriesMock[5],
    date: new Date(2022, 2, 4, 22, 0, 0, 0),
    description: 'Pago nomina',
    mount: 70000,
    type: TransactionType.INCOMES,
  },
];
